name: Update Build

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'receptron'
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: yarn install
    - run: yarn b
    - run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add lib/*
    - name: Commit 
      run: |
        if [ $(git diff --name-only --cached | wc -l) != 0 ]; then
          git commit -m "Update lib" lib/
          git push origin main
        else
          echo "No change on lib"
        fi
    - name: Commit 
      run: |
        if [ $(git diff | wc -l) != 0 ]; then
          git commit -m "format" .
          git push origin main
        else
          echo "No change format"
        fi
